services:
  - type: web
    name: digiverse-domain
    env: python
    region: oregon  # Or choose your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

build:
  envVars:
    - key: FLASK_ENV
      value: production
